name: osv-scanner

on:
  schedule:
    - cron: '25 20 * * 4'
  push:
    branches: [ main ]

# Declare default permissions as read only.
permissions: 
  security-events: write
  contents: read

jobs:
  scan-pr-attempt:
    uses: "google/osv-scanner/.github/workflows/osv-scanner-reusable-scheduled.yml@main"
    # with:
    #   scan-args: |-
    #     -r
    #     ./
