name: osv-scanner

on:
  schedule:
    - cron: '0,10,20,30,40,50 16,17 * * *'
  push:
    branches: [ "main" ]

# Declare default permissions as read only.
permissions: 
  security-events: write
  contents: read

jobs:
  scan-pr-attempt:
    uses: "google/osv-scanner/.github/workflows/osv-scanner-reusable-scheduled.yml@main"
