name: osv-scanner

on:
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]
  merge_group:
    branches: [ main ]

# Declare default permissions as read only.
permissions: read-all

jobs:
  scan-pr-attempt:
    uses: "google/osv-scanner/.github/workflows/osv-scanner-reusable-pr.yml@main"
